### ISSUE TITLE
Works with Maven 3.0.5, but fails with Maven 3.1.1, 3.2.5 and 3.3.3 and maybe others

### ISSUE THREAD

**Issue by dholzenburg** [smoope/j2objc-maven-plugin#1]
Hi,

first of all, thank you for providing this plugin. It's very helpful in my opinion.

I had problems using it with Maven 3.3.3. It works with Maven 3.0.5 (version bundled with Netbeans). I tried versions 3.1.1 and 3.2.5 and it failed as well. Using versions >= 3.1.x it complains about

java.lang.ClassNotFoundException: org.sonatype.aether.resolution.DependencyResolutionException

This issue seems to be known: https://cwiki.apache.org/confluence/display/MAVEN/AetherClassNotFound

Which version of Maven do you use?

This is my full output using Maven 3.2.5:

cd /Users/blabla/NetBeansProjects/j2objc-test; JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home M2_HOME=/opt/apache-maven-3.2.5 /opt/apache-maven-3.2.5/bin/mvn j2objc:convert
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building j2objc-test 0.1
------------------------------------------------------------------------

--- j2objc-maven-plugin:1.0.0:convert (default-cli) @ j2objc-test ---
Error injecting: com.smoope.utils.J2ObjCConverterMojo
java.lang.NoClassDefFoundError: org/sonatype/aether/resolution/DependencyResolutionException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	at java.lang.Class.getDeclaredConstructors(Class.java:2007)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:99)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:657)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:875)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:798)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:281)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:213)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:998)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1031)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:994)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:54)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:113)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:122)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:46)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:464)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:119)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.sonatype.aether.resolution.DependencyResolutionException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 54 more
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1.354 s
Finished at: 2016-01-07T12:51:05+01:00
Final Memory: 9M/176M
------------------------------------------------------------------------
Failed to execute goal com.smoope.utils:j2objc-maven-plugin:1.0.0:convert (default-cli) on project j2objc-test: Execution default-cli of goal com.smoope.utils:j2objc-maven-plugin:1.0.0:convert failed: A required class was missing while executing com.smoope.utils:j2objc-maven-plugin:1.0.0:convert: org/sonatype/aether/resolution/DependencyResolutionException
-----------------------------------------------------
realm =    plugin>com.smoope.utils:j2objc-maven-plugin:1.0.0
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/blabla/.m2/repository/com/smoope/utils/j2objc-maven-plugin/1.0.0/j2objc-maven-plugin-1.0.0.jar
urls[1] = file:/Users/blabla/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
urls[2] = file:/Users/blabla/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
urls[3] = file:/Users/blabla/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar
urls[4] = file:/Users/blabla/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar
urls[5] = file:/Users/blabla/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[6] = file:/Users/blabla/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
urls[7] = file:/Users/blabla/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
urls[8] = file:/Users/blabla/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
urls[9] = file:/Users/blabla/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
urls[10] = file:/Users/blabla/.m2/repository/com/jcabi/jcabi-aether/0.10.1/jcabi-aether-0.10.1.jar
urls[11] = file:/Users/blabla/.m2/repository/org/hibernate/hibernate-validator/5.1.2.Final/hibernate-validator-5.1.2.Final.jar
urls[12] = file:/Users/blabla/.m2/repository/org/jboss/logging/jboss-logging/3.1.3.GA/jboss-logging-3.1.3.GA.jar
urls[13] = file:/Users/blabla/.m2/repository/com/fasterxml/classmate/1.0.0/classmate-1.0.0.jar
urls[14] = file:/Users/blabla/.m2/repository/com/jcabi/jcabi-aspects/0.18/jcabi-aspects-0.18.jar
urls[15] = file:/Users/blabla/.m2/repository/com/jcabi/jcabi-log/0.14.3/jcabi-log-0.14.3.jar
urls[16] = file:/Users/blabla/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
urls[17] = file:/Users/blabla/.m2/repository/org/aspectj/aspectjrt/1.8.2/aspectjrt-1.8.2.jar
urls[18] = file:/Users/blabla/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
urls[19] = file:/Users/blabla/.m2/repository/org/kuali/maven/wagons/maven-s3-wagon/1.1.20/maven-s3-wagon-1.1.20.jar
urls[20] = file:/Users/blabla/.m2/repository/org/kuali/common/kuali-s3/1.0.1/kuali-s3-1.0.1.jar
urls[21] = file:/Users/blabla/.m2/repository/com/amazonaws/aws-java-sdk/1.4.2/aws-java-sdk-1.4.2.jar
urls[22] = file:/Users/blabla/.m2/repository/org/apache/httpcomponents/httpclient/4.1/httpclient-4.1.jar
urls[23] = file:/Users/blabla/.m2/repository/org/apache/httpcomponents/httpcore/4.1/httpcore-4.1.jar
urls[24] = file:/Users/blabla/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar
urls[25] = file:/Users/blabla/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.8.9/jackson-core-asl-1.8.9.jar
urls[26] = file:/Users/blabla/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.8.9/jackson-mapper-asl-1.8.9.jar
urls[27] = file:/Users/blabla/.m2/repository/org/springframework/spring-core/3.1.2.RELEASE/spring-core-3.1.2.RELEASE.jar
urls[28] = file:/Users/blabla/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
urls[29] = file:/Users/blabla/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
urls[30] = file:/Users/blabla/.m2/repository/org/kuali/common/kuali-threads/1.0.9/kuali-threads-1.0.9.jar
urls[31] = file:/Users/blabla/.m2/repository/org/slf4j/jcl-over-slf4j/1.6.4/jcl-over-slf4j-1.6.4.jar
urls[32] = file:/Users/blabla/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
urls[33] = file:/Users/blabla/.m2/repository/org/sonatype/aether/aether-connector-file/1.13.1/aether-connector-file-1.13.1.jar
urls[34] = file:/Users/blabla/.m2/repository/org/sonatype/aether/aether-connector-asynchttpclient/1.13.1/aether-connector-asynchttpclient-1.13.1.jar
urls[35] = file:/Users/blabla/.m2/repository/com/ning/async-http-client/1.6.5/async-http-client-1.6.5.jar
urls[36] = file:/Users/blabla/.m2/repository/org/jboss/netty/netty/3.2.5.Final/netty-3.2.5.Final.jar
urls[37] = file:/Users/blabla/.m2/repository/org/sonatype/aether/aether-connector-wagon/1.13.1/aether-connector-wagon-1.13.1.jar
urls[38] = file:/Users/blabla/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.2.3/sisu-inject-bean-2.2.3.jar
urls[39] = file:/Users/blabla/.m2/repository/org/sonatype/sisu/sisu-guice/3.0.3/sisu-guice-3.0.3-no_aop.jar
urls[40] = file:/Users/blabla/.m2/repository/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
urls[41] = file:/Users/blabla/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.1/maven-dependency-tree-2.1.jar
urls[42] = file:/Users/blabla/.m2/repository/org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------: org.sonatype.aether.resolution.DependencyResolutionException
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/AetherClassNotFound

**Comment by vicmosin** [comment]
Hi, thanks for response.
Yes, you are right, it is indeed https://cwiki.apache.org/confluence/display/MAVEN/AetherClassNotFound.

I released 1.0.1 but it will take some time until you can get it from maven central repo. Meanwhile you can try 1.0.1-SNAPSHOT

**Comment by dholzenburg** [comment]
Hi Victor,

thank you very much for this fast solution. It works perfectly.

**Comment by adam-rocska** [comment]
@dholzenburg  With Maven `3.6.1` the issue is back (I guess) : "Build error - dependency resolution failed".

Any guesses maybe?
